### PR TITLE
Close file at the end

### PR DESCRIPTION
**Pull request by Amaroq7**
File should be closed at the end.

### CODE REVIEW

**Comment by Arkshine** [comment]
I did not expect someone checking such branch! 

Thanks.

**Comment by Amaroq7** [comment]
I want to see this merged into master branch :smiling_imp:

**Comment by Arkshine** [comment]
Ahah, yeah me too. There is still few things I don't like much.
For example `set_task(6.2 ...` is really silly. It's because `admin.sma` loads config files after 6.1 seconds for some reasons... We need a forward like `OnConfigsExecuted` or similar and such things should be done in core, not plugins.

**Comment by Amaroq7** [comment]
It would be great to see that feature in amxx. Do you have any plans to implement it?

**Pull request merged**
